### ISSUE TITLE
Allow finding the current configured secret

### ISSUE THREAD

**Issue by aloisklink** [nqminds/nqm-tdx-terminal-cli#4]
There doesn't seem to be a way to get the currently used credentials. `tdxcli -t tdx.config.json -a tdxopenapi list` ignores credentials set via  `$TDX_CREDENTIALS`.

`TDX_CREDENTIALS="$base64jsonresult" npx tdxcli -t tdx.config.json -a tdxopenapi config` seems to return something that looks similar to the `CommandHandler` object. Maybe we could add the currently configured secret to that? e.g. replacing line https://github.com/nqminds/nqm-tdx-terminal-cli/blob/47bd560dafaecc14b44025a6d09af9edc4d7c897/main.js#L154 to:

```js
class CommandHandler {
...
  // maybe add a --show-secret cmd-line flag if we're worried about security
  getConfig(showSecret=false) { 
    const additionalProps = {};
    if (showSecret) additionalProps.secret = this.secret;
    return {
      tokenHref: this.tokenHref,
      config: this.config,
      ...additionalProps,
  }
...
const output = commandHandler.getConfig(); // main.js#L154
```

**Comment by mereacre** [comment]
I did a revision of the code and I think the ```list``` command should return only the stored secrets in the .env file. Even if one uses ```TDX_CREDENTIALS``` the ```list``` should still return the stored secrets.
